### ISSUE TITLE
Tags/ releases missing in repository

### ISSUE THREAD

**Issue by dvzrv** [sde1000/python-xkbcommon#9]
Hi! I'm currently trying to package python-xkbcommon for Arch Linux.

Unfortunately this project is missing the tags that led to the sdist tarballs on pypi.org: https://pypi.org/project/xkbcommon/#history

Can you please tag the versions? This ensures transparency during bug reports and when building from source. Especially for downstream distributions this is very important to guard against supply chain attacks and to be able to run tests (currently I can not switch to an auto-generated github release tarball, which includes the tests, as there are none).

Thanks!

**Comment by sde1000** [comment]
I've added tags for v0.2 and v0.3. I can't identify which commit corresponds to v0.1 because there are two possibilities and the download link for 0.1 is no longer present on pypi.org

Pull request #12 updates the packaging and is a draft for release 0.4. If it fixes all the issues you've identified, please let me know and then I'll merge it, tag it, and upload the sdist to pypi.org

**Comment by sde1000** [comment]
Version 0.4 tagged and uploaded to pypi.org
